### PR TITLE
Fixing a bug

### PR DESCRIPTION
**Pull request by primis**
Forgot to include the assembly source files.
I tried to compile and there were a bunch of missing symbols!
This should fix it up...

### CODE REVIEW

**Comment by bjm1904** [comment]
Thanks for that. Good catch!

Can you be more descriptive with the commit messages? Using git log is often quicker than having to rummage through github's activity log.

**Comment by primis** [comment]
My Apologies.

**Comment by dxywx** [comment]
@bjm1904 Hello , do you have makefile for windows ?

**Comment by bjm1904** [comment]
@dxywx Don't take it the wrong way, but I would strongly suggest you spend time working on other projects before going any further. This question betrays a lack of programming experience, and as the teen-aged me learned the hard way this is not a good thing when it comes to kernel development.

In case you choose to ignore that advice (just as I did when I heard it!): Makefiles are platform neutral, you just need to have make, the relevant assemblers, compilers and linkers in your PATH variable to make it work. I would recommend using MinGW or Linux in a VM and taking a look at http://wiki.osdev.org to find out how to do kernel/cross-compilation.

**Comment by dxywx** [comment]
@bjm1904 Thanks , kernel development is one of my interests , but I don't have any experiences on it . I will follow you advice .

**Pull request merged**
